version: "3.9"

services:
  api:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    env_file:
      - ./.env.prod
    entrypoint: ./docker-entrypoint.sh
